//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  bio: Bio;
  bioConnection: BioConnection;
  research: Research;
  researchConnection: ResearchConnection;
  activism: Activism;
  activismConnection: ActivismConnection;
  outreach: Outreach;
  outreachConnection: OutreachConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  cv: Cv;
  cvConnection: CvConnection;
  publications: Publications;
  publicationsConnection: PublicationsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBioArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBioConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BioFilter>;
};


export type QueryResearchArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearchConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
};


export type QueryActivismArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryActivismConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActivismFilter>;
};


export type QueryOutreachArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOutreachConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OutreachFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryCvArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCvConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CvFilter>;
};


export type QueryPublicationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPublicationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationsFilter>;
};

export type DocumentFilter = {
  bio?: InputMaybe<BioFilter>;
  research?: InputMaybe<ResearchFilter>;
  activism?: InputMaybe<ActivismFilter>;
  outreach?: InputMaybe<OutreachFilter>;
  services?: InputMaybe<ServicesFilter>;
  contact?: InputMaybe<ContactFilter>;
  cv?: InputMaybe<CvFilter>;
  publications?: InputMaybe<PublicationsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Bio | Research | Activism | Outreach | Services | Contact | Cv | Publications | Folder;

export type BioSocial = {
  __typename?: 'BioSocial';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Bio = Node & Document & {
  __typename?: 'Bio';
  title?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  social?: Maybe<Array<Maybe<BioSocial>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BioSocialFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BioFilter = {
  title?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  email?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  social?: InputMaybe<BioSocialFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BioConnectionEdges = {
  __typename?: 'BioConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Bio>;
};

export type BioConnection = Connection & {
  __typename?: 'BioConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BioConnectionEdges>>>;
};

export type Research = Node & Document & {
  __typename?: 'Research';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  openLinksInNewTab?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ResearchFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  order?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  openLinksInNewTab?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ResearchConnectionEdges = {
  __typename?: 'ResearchConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Research>;
};

export type ResearchConnection = Connection & {
  __typename?: 'ResearchConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResearchConnectionEdges>>>;
};

export type Activism = Node & Document & {
  __typename?: 'Activism';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  openLinksInNewTab?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ActivismFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  order?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  openLinksInNewTab?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ActivismConnectionEdges = {
  __typename?: 'ActivismConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Activism>;
};

export type ActivismConnection = Connection & {
  __typename?: 'ActivismConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ActivismConnectionEdges>>>;
};

export type Outreach = Node & Document & {
  __typename?: 'Outreach';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  openLinksInNewTab?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OutreachFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  order?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  openLinksInNewTab?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type OutreachConnectionEdges = {
  __typename?: 'OutreachConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Outreach>;
};

export type OutreachConnection = Connection & {
  __typename?: 'OutreachConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OutreachConnectionEdges>>>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  openLinksInNewTab?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  backgroundColor?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  order?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  openLinksInNewTab?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
  backgroundColor?: InputMaybe<StringFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  title: Scalars['String']['output'];
  backgroundImage?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  title?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Cv = Node & Document & {
  __typename?: 'Cv';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  openLinksInNewTab?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CvFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  order?: InputMaybe<NumberFilter>;
  image?: InputMaybe<ImageFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  openLinksInNewTab?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type CvConnectionEdges = {
  __typename?: 'CvConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Cv>;
};

export type CvConnection = Connection & {
  __typename?: 'CvConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CvConnectionEdges>>>;
};

export type Publications = Node & Document & {
  __typename?: 'Publications';
  title: Scalars['String']['output'];
  venue?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  authors?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PublicationsFilter = {
  title?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  url?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  authors?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PublicationsConnectionEdges = {
  __typename?: 'PublicationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Publications>;
};

export type PublicationsConnection = Connection & {
  __typename?: 'PublicationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PublicationsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBio: Bio;
  createBio: Bio;
  updateResearch: Research;
  createResearch: Research;
  updateActivism: Activism;
  createActivism: Activism;
  updateOutreach: Outreach;
  createOutreach: Outreach;
  updateServices: Services;
  createServices: Services;
  updateContact: Contact;
  createContact: Contact;
  updateCv: Cv;
  createCv: Cv;
  updatePublications: Publications;
  createPublications: Publications;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBioArgs = {
  relativePath: Scalars['String']['input'];
  params: BioMutation;
};


export type MutationCreateBioArgs = {
  relativePath: Scalars['String']['input'];
  params: BioMutation;
};


export type MutationUpdateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationCreateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationUpdateActivismArgs = {
  relativePath: Scalars['String']['input'];
  params: ActivismMutation;
};


export type MutationCreateActivismArgs = {
  relativePath: Scalars['String']['input'];
  params: ActivismMutation;
};


export type MutationUpdateOutreachArgs = {
  relativePath: Scalars['String']['input'];
  params: OutreachMutation;
};


export type MutationCreateOutreachArgs = {
  relativePath: Scalars['String']['input'];
  params: OutreachMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateCvArgs = {
  relativePath: Scalars['String']['input'];
  params: CvMutation;
};


export type MutationCreateCvArgs = {
  relativePath: Scalars['String']['input'];
  params: CvMutation;
};


export type MutationUpdatePublicationsArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationsMutation;
};


export type MutationCreatePublicationsArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationsMutation;
};

export type DocumentUpdateMutation = {
  bio?: InputMaybe<BioMutation>;
  research?: InputMaybe<ResearchMutation>;
  activism?: InputMaybe<ActivismMutation>;
  outreach?: InputMaybe<OutreachMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
  cv?: InputMaybe<CvMutation>;
  publications?: InputMaybe<PublicationsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  bio?: InputMaybe<BioMutation>;
  research?: InputMaybe<ResearchMutation>;
  activism?: InputMaybe<ActivismMutation>;
  outreach?: InputMaybe<OutreachMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
  cv?: InputMaybe<CvMutation>;
  publications?: InputMaybe<PublicationsMutation>;
};

export type BioSocialMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type BioMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  social?: InputMaybe<Array<InputMaybe<BioSocialMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ResearchMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  openLinksInNewTab?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ActivismMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  openLinksInNewTab?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type OutreachMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  openLinksInNewTab?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ServicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  openLinksInNewTab?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  backgroundColor?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
};

export type CvMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  openLinksInNewTab?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PublicationsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  authors?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BioPartsFragment = { __typename: 'Bio', title?: string | null, role?: string | null, image?: string | null, backgroundImage?: string | null, email?: string | null, address?: string | null, body?: any | null, social?: Array<{ __typename: 'BioSocial', label?: string | null, url?: string | null } | null> | null };

export type ResearchPartsFragment = { __typename: 'Research', title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null };

export type ActivismPartsFragment = { __typename: 'Activism', title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null };

export type OutreachPartsFragment = { __typename: 'Outreach', title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null };

export type ServicesPartsFragment = { __typename: 'Services', title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, backgroundColor?: string | null };

export type ContactPartsFragment = { __typename: 'Contact', title: string, backgroundImage?: string | null };

export type CvPartsFragment = { __typename: 'Cv', title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null };

export type PublicationsPartsFragment = { __typename: 'Publications', title: string, venue?: string | null, year?: number | null, url?: string | null, backgroundImage?: string | null, authors?: Array<string | null> | null, body?: any | null };

export type BioQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BioQuery = { __typename?: 'Query', bio: { __typename: 'Bio', id: string, title?: string | null, role?: string | null, image?: string | null, backgroundImage?: string | null, email?: string | null, address?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: Array<{ __typename: 'BioSocial', label?: string | null, url?: string | null } | null> | null } };

export type BioConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BioFilter>;
}>;


export type BioConnectionQuery = { __typename?: 'Query', bioConnection: { __typename?: 'BioConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BioConnectionEdges', cursor: string, node?: { __typename: 'Bio', id: string, title?: string | null, role?: string | null, image?: string | null, backgroundImage?: string | null, email?: string | null, address?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: Array<{ __typename: 'BioSocial', label?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export type ResearchQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResearchQuery = { __typename?: 'Query', research: { __typename: 'Research', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResearchConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
}>;


export type ResearchConnectionQuery = { __typename?: 'Query', researchConnection: { __typename?: 'ResearchConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResearchConnectionEdges', cursor: string, node?: { __typename: 'Research', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ActivismQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ActivismQuery = { __typename?: 'Query', activism: { __typename: 'Activism', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ActivismConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActivismFilter>;
}>;


export type ActivismConnectionQuery = { __typename?: 'Query', activismConnection: { __typename?: 'ActivismConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ActivismConnectionEdges', cursor: string, node?: { __typename: 'Activism', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type OutreachQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OutreachQuery = { __typename?: 'Query', outreach: { __typename: 'Outreach', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type OutreachConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OutreachFilter>;
}>;


export type OutreachConnectionQuery = { __typename?: 'Query', outreachConnection: { __typename?: 'OutreachConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OutreachConnectionEdges', cursor: string, node?: { __typename: 'Outreach', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, backgroundColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, backgroundColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, title: string, backgroundImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, title: string, backgroundImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CvQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CvQuery = { __typename?: 'Query', cv: { __typename: 'Cv', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CvConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CvFilter>;
}>;


export type CvConnectionQuery = { __typename?: 'Query', cvConnection: { __typename?: 'CvConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CvConnectionEdges', cursor: string, node?: { __typename: 'Cv', id: string, title: string, description?: string | null, date?: string | null, order?: number | null, image?: string | null, backgroundImage?: string | null, openLinksInNewTab?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PublicationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PublicationsQuery = { __typename?: 'Query', publications: { __typename: 'Publications', id: string, title: string, venue?: string | null, year?: number | null, url?: string | null, backgroundImage?: string | null, authors?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PublicationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationsFilter>;
}>;


export type PublicationsConnectionQuery = { __typename?: 'Query', publicationsConnection: { __typename?: 'PublicationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PublicationsConnectionEdges', cursor: string, node?: { __typename: 'Publications', id: string, title: string, venue?: string | null, year?: number | null, url?: string | null, backgroundImage?: string | null, authors?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BioPartsFragmentDoc = gql`
    fragment BioParts on Bio {
  __typename
  title
  role
  image
  backgroundImage
  email
  address
  social {
    __typename
    label
    url
  }
  body
}
    `;
export const ResearchPartsFragmentDoc = gql`
    fragment ResearchParts on Research {
  __typename
  title
  description
  date
  order
  image
  backgroundImage
  openLinksInNewTab
  body
}
    `;
export const ActivismPartsFragmentDoc = gql`
    fragment ActivismParts on Activism {
  __typename
  title
  description
  date
  order
  image
  backgroundImage
  openLinksInNewTab
  body
}
    `;
export const OutreachPartsFragmentDoc = gql`
    fragment OutreachParts on Outreach {
  __typename
  title
  description
  date
  order
  image
  backgroundImage
  openLinksInNewTab
  body
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  title
  description
  date
  order
  image
  backgroundImage
  openLinksInNewTab
  body
  backgroundColor
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  title
  backgroundImage
}
    `;
export const CvPartsFragmentDoc = gql`
    fragment CvParts on Cv {
  __typename
  title
  description
  date
  order
  image
  backgroundImage
  openLinksInNewTab
  body
}
    `;
export const PublicationsPartsFragmentDoc = gql`
    fragment PublicationsParts on Publications {
  __typename
  title
  venue
  year
  url
  backgroundImage
  authors
  body
}
    `;
export const BioDocument = gql`
    query bio($relativePath: String!) {
  bio(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BioParts
  }
}
    ${BioPartsFragmentDoc}`;
export const BioConnectionDocument = gql`
    query bioConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BioFilter) {
  bioConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BioParts
      }
    }
  }
}
    ${BioPartsFragmentDoc}`;
export const ResearchDocument = gql`
    query research($relativePath: String!) {
  research(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResearchParts
  }
}
    ${ResearchPartsFragmentDoc}`;
export const ResearchConnectionDocument = gql`
    query researchConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResearchFilter) {
  researchConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResearchParts
      }
    }
  }
}
    ${ResearchPartsFragmentDoc}`;
export const ActivismDocument = gql`
    query activism($relativePath: String!) {
  activism(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ActivismParts
  }
}
    ${ActivismPartsFragmentDoc}`;
export const ActivismConnectionDocument = gql`
    query activismConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ActivismFilter) {
  activismConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ActivismParts
      }
    }
  }
}
    ${ActivismPartsFragmentDoc}`;
export const OutreachDocument = gql`
    query outreach($relativePath: String!) {
  outreach(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OutreachParts
  }
}
    ${OutreachPartsFragmentDoc}`;
export const OutreachConnectionDocument = gql`
    query outreachConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OutreachFilter) {
  outreachConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OutreachParts
      }
    }
  }
}
    ${OutreachPartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const CvDocument = gql`
    query cv($relativePath: String!) {
  cv(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CvParts
  }
}
    ${CvPartsFragmentDoc}`;
export const CvConnectionDocument = gql`
    query cvConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CvFilter) {
  cvConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CvParts
      }
    }
  }
}
    ${CvPartsFragmentDoc}`;
export const PublicationsDocument = gql`
    query publications($relativePath: String!) {
  publications(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PublicationsParts
  }
}
    ${PublicationsPartsFragmentDoc}`;
export const PublicationsConnectionDocument = gql`
    query publicationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PublicationsFilter) {
  publicationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PublicationsParts
      }
    }
  }
}
    ${PublicationsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      bio(variables: BioQueryVariables, options?: C): Promise<{data: BioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioQueryVariables, query: string}> {
        return requester<{data: BioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioQueryVariables, query: string}, BioQueryVariables>(BioDocument, variables, options);
      },
    bioConnection(variables?: BioConnectionQueryVariables, options?: C): Promise<{data: BioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioConnectionQueryVariables, query: string}> {
        return requester<{data: BioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioConnectionQueryVariables, query: string}, BioConnectionQueryVariables>(BioConnectionDocument, variables, options);
      },
    research(variables: ResearchQueryVariables, options?: C): Promise<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}> {
        return requester<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}, ResearchQueryVariables>(ResearchDocument, variables, options);
      },
    researchConnection(variables?: ResearchConnectionQueryVariables, options?: C): Promise<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}> {
        return requester<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}, ResearchConnectionQueryVariables>(ResearchConnectionDocument, variables, options);
      },
    activism(variables: ActivismQueryVariables, options?: C): Promise<{data: ActivismQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivismQueryVariables, query: string}> {
        return requester<{data: ActivismQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivismQueryVariables, query: string}, ActivismQueryVariables>(ActivismDocument, variables, options);
      },
    activismConnection(variables?: ActivismConnectionQueryVariables, options?: C): Promise<{data: ActivismConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivismConnectionQueryVariables, query: string}> {
        return requester<{data: ActivismConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivismConnectionQueryVariables, query: string}, ActivismConnectionQueryVariables>(ActivismConnectionDocument, variables, options);
      },
    outreach(variables: OutreachQueryVariables, options?: C): Promise<{data: OutreachQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutreachQueryVariables, query: string}> {
        return requester<{data: OutreachQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutreachQueryVariables, query: string}, OutreachQueryVariables>(OutreachDocument, variables, options);
      },
    outreachConnection(variables?: OutreachConnectionQueryVariables, options?: C): Promise<{data: OutreachConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutreachConnectionQueryVariables, query: string}> {
        return requester<{data: OutreachConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutreachConnectionQueryVariables, query: string}, OutreachConnectionQueryVariables>(OutreachConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    cv(variables: CvQueryVariables, options?: C): Promise<{data: CvQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvQueryVariables, query: string}> {
        return requester<{data: CvQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvQueryVariables, query: string}, CvQueryVariables>(CvDocument, variables, options);
      },
    cvConnection(variables?: CvConnectionQueryVariables, options?: C): Promise<{data: CvConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvConnectionQueryVariables, query: string}> {
        return requester<{data: CvConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvConnectionQueryVariables, query: string}, CvConnectionQueryVariables>(CvConnectionDocument, variables, options);
      },
    publications(variables: PublicationsQueryVariables, options?: C): Promise<{data: PublicationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsQueryVariables, query: string}> {
        return requester<{data: PublicationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsQueryVariables, query: string}, PublicationsQueryVariables>(PublicationsDocument, variables, options);
      },
    publicationsConnection(variables?: PublicationsConnectionQueryVariables, options?: C): Promise<{data: PublicationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsConnectionQueryVariables, query: string}> {
        return requester<{data: PublicationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsConnectionQueryVariables, query: string}, PublicationsConnectionQueryVariables>(PublicationsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  